sudo: required
dist: trusty
language: generic
env:
  - ROS_DISTRO="indigo"
  - ROS_DISTRO="kinetic"
  - ROS_DISTRO="melodic"
  - ROS_DISTRO="noetic"
install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config
  - pip install flatten-dict --user
  - pip install tqdm --user
script:
  - source .ci_config/travis.sh
