#!/usr/bin/env python

import argparse
import logging

import matplotlib.pyplot as plt
import rosbag_parquet
from rosbag_parquet.utils import topics_from_keys


def build_parser():
    """
    Builds the parser for reading the command line arguments
    :return: Argument parser
    """
    parser = argparse.ArgumentParser(description='Bagfile key to graph')
    parser.add_argument('-b', '--bag', help='Bag file to read',
                        required=True, type=str)
    parser.add_argument('-k', '--key',
                        help='Key you would like to plot',
                        required=True, nargs='*')
    parser.add_argument('-y ', '--ylim',
                        help='Set min and max y lim',
                        required=False, nargs=2)
    parser.add_argument('-c', '--combined',
                        help="Graph them all on one",
                        required=False, action="store_true", dest="sharey")
    parser.add_argument('-v', '--verbose',
                        help="Log verbose",
                        default=False, action="store_true")
    return parser


def graph(dfs, keys, sharey):
    # Filter keys to those whose topic_name match and col from df matches
    keys = [key
            for key in keys
            if key.rsplit('/', maxsplit=1)[0] in dfs.keys()
            and key.rsplit('/', maxsplit=1)[1] in dfs[key.rsplit('/', maxsplit=1)[0]].columns]

    if sharey or len(keys) == 1:
        fig, axes = plt.subplots()
        for topic_name, df in dfs.items():
            for key in keys:
                key = key.strip(topic_name + '/')
                if key in df.columns:
                    s = df[key].dropna()
                    time = df['time'].dropna()
                    axes.plot(time, s.values, label=key)

        axes.legend(loc=0)
        plt.show()
    else:
        fig, axes = plt.subplots(len(keys), sharex=True)
        idx = 0
        for topic_name, df in dfs.items():
            for key in keys:
                key = key.strip(topic_name + '/')
                if key in df.columns:
                    s = df[key].dropna()
                    time = df['time'].dropna()
                    axes[idx].plot(time, s.values)
                    axes[idx].set_title(key)
                    idx = idx + 1
        plt.show()


if __name__ == '__main__':
    parser = build_parser()
    args = parser.parse_args()

    if args.verbose:
        logging.getLogger().setLevel(logging.DEBUG)

    topics = topics_from_keys(args.key)
    dfs = rosbag_parquet.bag_to_dataframes(args.bag, include=topics)
    graph(dfs, args.key, args.sharey)
