#!/usr/bin/env python

from __future__ import print_function

import argparse
import logging

import rosbag_parquet
from rosbag_parquet.utils import topics_from_keys


def build_parser():
    """
    Builds the parser for reading the command line arguments
    :return: Argument parser
    """
    parser = argparse.ArgumentParser(description='Print one or multiple bag keys')
    parser.add_argument('-b', '--bag', help='Bag file to read',
                        required=True, type=str)
    parser.add_argument('-k', '--key',
                        help='Key you would like to print',
                        required=True, nargs='*')
    parser.add_argument('-v', '--verbose',
                        help="Log verbose",
                        default=False, action="store_true")
    parser.add_argument('-s', '--show-progress',
                        help="Show progress bar",
                        default=False, action="store_true")
    return parser


if __name__ == '__main__':
    parser = build_parser()
    args = parser.parse_args()

    if args.verbose:
        logging.getLogger().setLevel(logging.DEBUG)

    topics = topics_from_keys(args.key)
    dfs = rosbag_parquet.bag_to_dataframes(args.bag, include=topics, show_progress=args.show_progress)
    topic_keys = {}
    for key in args.key:
        topic, key = key.rsplit('/', maxsplit=1)
        if topic not in topic_keys:
            topic_keys[topic] = []
        topic_keys[topic].append(key)
    for topic, keys in topic_keys.items():
        print(dfs[topic][keys].to_string())
